const validator = require('validator')
const add = require('./utils.js')
const getNotes = require('./index.js')
const Notes = getNotes()
console.log(Notes)
const sum = add(4,-2)
console.log(sum)
const fs = require('fs')
fs.writeFileSync('notes.txt', 'This file was created by node.js! Hello there')
fs.appendFileSync('notes.txt', "abc")